---
repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-json

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    name: black
    args: [--config, pyproject.toml, --verbose]

- repo: https://github.com/ikamensh/flynt/
  rev: '0.78'
  hooks:
  - id: flynt

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.10.0
  hooks:
  - id: reorder-python-imports

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.5
  hooks:
  - id: codespell

- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.3
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0']
