site_name: BIDS starter kit

theme:
  
  # material
#   name: material
  
  # cinder
  name: null
  custom_dir: 'cinder'

  favicon: images/favicon.png
  logo: images/logo.png

extra_javascript:
    - js/jquery-3.4.1.min.js

markdown_extensions:
    - toc:
        anchorlink: true
    - pymdownx.superfences

plugins:
    - search

docs_dir: 'src'

use_directory_urls: false

nav:
    - Home: index.md
    - Hierarchy:  
        Folders: folders.md
        Files: files.md
    - Tutorials: 
        iEEG: creating_iEEG_dataset.md
        others: tutorials.md
    - Ressources:
        Examples: examples.md
        Videos: videos.md 
        Publications: publications.md
        Links: links.md       
    - Validator: validator.md
    - BIDS-apps: apps.md
    - FAQ: FAQ.md
    - Glossary: glossary.md
    - Contact: contact.md


