[tool.black]
line-length = 99
target-version = ['py39']
exclude = '''
(
  /(
    tools/bids-specification       # exclude a few common directories in the root of the project
    | \.git
    | env
  )/
)
'''
