---
name: Check Markdown links

# checking for any dead links in markdown files

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - main
  pull_request:
    branches: ['*']

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: ./mlc_config.json
        folder-path: ./src/, templates
        use-verbose-mode: yes
        max-depth: -1
        file-path: ./README.md, ./CONTRIBUTING.md, ./CODE_OF_CONDUCT.md
