---
name: miss_hit

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - main
    paths:
    - '**.m'
  pull_request:
    branches: ['*']
    paths:
    - '**.m'

jobs:

  miss_hit:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        command: [mh_style, mh_metric --ci && mh_lint]
      fail-fast: true  # cancel all jobs if one fails

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip3 install -r requirements_dev.txt

    - name: ${{ matrix.command }}
      run: |
        ${{ matrix.command }}
